.gitignore, EvilGiraf.Tests/EvilGiraf.Tests.csproj, EvilGiraf.Tests/GlobalUsings.cs, EvilGiraf.Tests/UnitTest1.cs, EvilGiraf.sln
Added a new test project `EvilGiraf.Tests` with xUnit and necessary dependencies. Integrated it into the solution and updated `.gitignore` to exclude user-specific settings.
=> test: add initial unit test project setup

.github/workflows/sonarqube.yaml
Introduced a GitHub Actions workflow to integrate SonarQube analysis. This setup includes actions for caching, building, and running the SonarQube scanner with JDK 17 support. It helps ensure code quality through automated static analysis.
closes #4
=> ci: add SonarQube workflow for code analysis

EvilGiraf.Tests/EvilGiraf.Tests.csproj, EvilGiraf.Tests/UnitTest1.cs, EvilGiraf.Tests/WeatherForecastTests.cs
Introduce new unit tests to validate initialization and temperature conversion logic of the WeatherForecast model. Implemented FluentAssertions for enhanced readability and added a project reference to EvilGiraf.csproj.
=> test: add basic unit tests

.github/workflows/sonarqube.yaml, EvilGiraf.IntegrationTests/EvilGiraf.IntegrationTests.csproj, EvilGiraf.IntegrationTests/GlobalUsings.cs, EvilGiraf.IntegrationTests/WeatherForecastControllerTests.cs, EvilGiraf.sln, EvilGiraf/Program.cs
Added a new integration test project with tests for WeatherForecastController to validate API responses. Refactored the Program.cs file to include a `Program` namespace and class for better structuring. This improves test coverage and project organization.
Closes #5
=> test: add integration tests and restructure program entry point

.github/workflows/sonarqube.yaml
Moved coverage report path configuration to the analysis step to ensure correct integration. Removed redundant logic in the finalization step for cleaner workflow.
=> fix: adjust SonarQube analysis steps for coverage report

.github/workflows/sonarqube.yaml
Removed unnecessary steps, comments, and tools to streamline the workflow. Updated coverage report paths to directly use OpenCover format, reducing complexity and improving efficiency.
=> refactor: simplify SonarQube workflow and improve coverage handling

.github/workflows/ci.yml, .github/workflows/sonarqube.yaml
Renamed workflow and job names for clarity and consistency. Adjusted comments and steps in both SonarQube and CI workflows to improve readability and structure. No functional changes introduced.
=> refactor: update workflow names and job configurations

EvilGiraf/Controllers/WeatherForecastController.cs, EvilGiraf/Dockerfile
Added a log statement to the WeatherForecast controller for better traceability. Adjusted Dockerfile to ensure proper quoting of build configuration variables, addressing potential build issues.
=> fix: resolve logging and Dockerfile quoting issues (SonarQube issues)

EvilGiraf.IntegrationTests/ApplicationControllerTests.cs, EvilGiraf/Controllers/ApplicationController.cs, EvilGiraf/Dto/DeployDockerRequest.cs, EvilGiraf/Dto/DeployResponse.cs, EvilGiraf/Model/ApplicationStatus.cs
=> feat: application controller with deploy docker endpoint

EvilGiraf/Program.cs
Replaced lambda-based singleton registration with a generic type-based approach for `IDeploymentService`. This improves readability and aligns with standard dependency injection practices.
=> refactor: dependency injection for DeploymentService

.github/workflows/sonarqube.yaml
This updates the SonarQube GitHub Actions workflow to include .NET setup using version 8.0.x. The change ensures compatibility for projects requiring .NET during the analysis process.
=> fix: add .NET setup to SonarQube workflow

EvilGiraf/Interface/IApplicationService.cs, EvilGiraf/Program.cs, EvilGiraf/Service/ApplicationService.cs
Introduce a new scoped service, ApplicationService, to the DI container. Added IApplicationService interface and implemented it in ApplicationService. This improves service organization and enables better dependency injection practices.
Closes #42
=> feat: add ApplicationService and IApplicationService interface

.github/workflows/build.yml, .github/workflows/ci.yml, .github/workflows/deploy.yaml, .github/workflows/sonarqube.yaml
Updated all workflow files to use `github-runner-evilgiraf` instead of `github-runner`. This ensures consistency across build, deploy, SonarQube, and CI workflows.
=> chore(workflows): update runner to `github-runner-evilgiraf`

.github/workflows/sonarqube.yaml
Added GitVersion setup and version retrieval steps to the SonarQube workflow. The project version is now dynamically determined and passed to the SonarQube scanner for enhanced traceability and consistency.
=> ci: integrate GitVersion in Sonarqube for version management

EvilGiraf/Program.cs, EvilGiraf/Service/ApplicationService.cs, EvilGiraf/Service/DatabaseService.cs, EvilGiraf/Service/DeploymentService.cs
Removed redundant constructors, improved exception handling in DeploymentService by adding specific checks for 404 Not Found, and simplified GetApplication method in ApplicationService by removing unnecessary try-catch block. Added ExcludeFromCodeCoverage attribute to the Program class for better test coverage management. Minor cleanups to enhance code readability and maintainability.
=> chore: improve exception handling and code cleanup

EvilGiraf.IntegrationTests/ApplicationControllerTests.cs, EvilGiraf.Tests/ApplicationServiceTests.cs, EvilGiraf/Controller/ApplicationController.cs, EvilGiraf/Dto/ApplicationDto.cs, EvilGiraf/Extensions/ApplicationExtensions.cs, EvilGiraf/Interface/IApplicationService.cs, EvilGiraf/Service/ApplicationService.cs
This pull request introduces several changes to the `EvilGiraf` project, primarily focusing on refactoring the application creation process and improving the integration tests. The key changes include modifying the application creation DTOs, updating the controller and service layers, and adding integration tests.
* [`EvilGiraf/Dto/ApplicationDto.cs`](diffhunk://#diff-0bbd023732cbd1669f34aa6b4ae8266379f13336e002c451a018ce35e4e79aa8L5-R13): Introduced `ApplicationCreateDto` for application creation and `ApplicationResultDto` for the result, replacing the original `ApplicationDto`.
* [`EvilGiraf/Extensions/ApplicationExtensions.cs`](diffhunk://#diff-f3be140884794159d816d27976afcedaff01c33d826b0a622758331df9647e82R1-R29): Added extension methods `ToDto` and `ToModel` for converting between …
=> feat: Implement ApplicationController post endpoint

.github/workflows/deploy.yaml, EvilGiraf/Program.cs, helm-chart/Chart.yaml, helm-chart/templates/NOTES.txt, helm-chart/templates/_helpers.tpl, helm-chart/templates/deployment.yaml, helm-chart/templates/hpa.yaml, helm-chart/templates/ingress.yaml, helm-chart/templates/service.yaml, helm-chart/templates/serviceaccount.yaml, helm-chart/templates/tests/test-connection.yaml, helm-chart/values.yaml
Refactored Helm chart values to be more modular by nesting application-specific configs under `app`. Added PostgreSQL as a dependency with configurations. Introduced health checks and database migration as part of the deployment process.
Closes #77
=> feat: add PostgreSQL and restructure Helm chart for modularity

.github/workflows/CI.yml
Replaced manual Docker login with docker/login-action for improved readability and security. Integrated Docker Buildx and caching to optimize image builds, pulling from and pushing to the registry. Simplified image tagging and pushing steps for better maintainability.
Closes #96
=> ci: improve Docker workflow with Buildx and caching

.github/workflows/CD.yaml, EvilGiraf.Front/Dockerfile, helm-chart/templates/_helpers.tpl, helm-chart/templates/deployment-api.yaml, helm-chart/templates/deployment-front.yaml, helm-chart/templates/hpa-api.yaml, helm-chart/templates/hpa-front.yaml, helm-chart/templates/ingress-api.yaml, helm-chart/templates/ingress-front.yaml, helm-chart/templates/rbac-api.yaml, helm-chart/templates/rbac-front.yaml, helm-chart/templates/service-api.yaml, helm-chart/templates/service-front.yaml, helm-chart/templates/serviceaccount-api.yaml, helm-chart/templates/serviceaccount-front.yaml, helm-chart/templates/tests/test-connection.yaml, helm-chart/values.yaml
Separated API and frontend configurations in Helm chart, introducing independent values for `api` and `front` components. Added templates for frontend deployment, service, ingress, HPA, and service account, along with customization options. Updated CI/CD workflow to support the new structure.
Closes #128
=> feat: add frontend deployment and API-specific configurations

EvilGiraf.IntegrationTests/ApplicationControllerTests.cs, EvilGiraf.IntegrationTests/CustomWebApplicationFactory.cs, EvilGiraf.IntegrationTests/DeploymentControllerTests.cs, EvilGiraf.IntegrationTests/IntegrationTestBase.cs, EvilGiraf.Tests/ApplicationTests.cs
Removed redundant test cases, unused variables, and unnecessary dependencies to streamline the codebase. Simplified logic in integration tests and adjusted test naming conventions for consistency. These changes improve maintainability and reduce duplication.
=> refactor: tests and clean up unused code

EvilGiraf.IntegrationTests/DeploymentControllerTests.cs, EvilGiraf.Tests/GitBuildTests.cs, EvilGiraf.Tests/KubernetesTests.cs, EvilGiraf.Tests/NamespaceTests.cs, EvilGiraf/Controller/DeploymentController.cs, EvilGiraf/Exceptions.cs, EvilGiraf/Interface/IGitBuildService.cs, EvilGiraf/Interface/IKubernetesService.cs, EvilGiraf/Interface/Kubernetes/INamespaceService.cs, EvilGiraf/Program.cs, EvilGiraf/Service/GitBuildService.cs, EvilGiraf/Service/Kubernetes/NamespaceService.cs, EvilGiraf/Service/KubernetesService.cs, EvilGiraf/appsettings.json
Introduced IGitBuildService and its implementation to handle building and pushing Docker images from Git repositories. Updated KubernetesService to integrate this workflow, conditionally building images for Git-based applications before deployment. Extended configuration to include Docker registry settings and added a new ConfigurationException for missing configurations.
Closes #78
=> feat: add Git-based Docker build and push workflow

EvilGiraf.IntegrationTests/ApplicationControllerTests.cs, EvilGiraf.IntegrationTests/DeploymentControllerTests.cs, EvilGiraf.Tests/ApplicationTests.cs, EvilGiraf.Tests/IngressTests.cs, EvilGiraf.Tests/KubernetesTests.cs, EvilGiraf/Dto/ApplicationDto.cs, EvilGiraf/Extensions/ApplicationExtensions.cs, EvilGiraf/Interface/Kubernetes/IIngressService.cs, EvilGiraf/Migrations/20250413195441_ApplicationIngress.Designer.cs, EvilGiraf/Migrations/20250413195441_ApplicationIngress.cs, EvilGiraf/Model/Application.cs, EvilGiraf/Model/IngressModel.cs, EvilGiraf/Program.cs, EvilGiraf/Service/ApplicationService.cs, EvilGiraf/Service/Kubernetes/IngressService.cs, EvilGiraf/Service/Kubernetes/ServiceService.cs, EvilGiraf/Service/KubernetesService.cs
Added Domain Name to Application
Created IngressService and updated IngressModel
Added Ingress creation in KubernetesService
Closes #99
=> feat : Added support for Ingresses

EvilGiraf.Front/src/pages/ApplicationDetails.tsx, EvilGiraf.Front/src/pages/Applications.tsx, EvilGiraf.Front/src/types/api.ts
Introduce domain name field to applications, allowing users to specify a domain name if a port is set. Updated form handling, validation, and display logic to accommodate the new field.
=> feat: add domain name support for applications

LICENSE, README.md, docs/CONTRIBUTING.md, docs/README.md, docs/api/README.md, docs/deployment/README.md, docs/frontend/README.md, docs/getting-started/README.md
=> docs: add comprehensive documentation including LICENSE, contributing guide, deployment instructions, and frontend usage
