- .github/workflows/sonarqube.yaml
Moved the SonarQube analysis step to run before building the project. This change ensures accurate code analysis and coverage reporting. The functionality remains unaffected; only the workflow order is updated.
> fix: SonarQube analysis step

- .github/workflows/ci.yml
Removed pull_request from the workflow triggers to avoid redundant CI runs. This change ensures the tests run exclusively on push events, streamlining the CI process.
> fix: trigger workflow only on push events

- EvilGiraf.IntegrationTests/ApplicationControllerTests.cs
Add tests to ensure the deploy endpoints return BadRequest when the "Name" or "Link" fields are empty for both Docker and GitHub deployment routes. This improves coverage for edge cases and ensures proper validation behavior.
> test: add validation tests for empty fields in deploy endpoints

- Dockerfile
- EvilGiraf/Program.cs
Moved Swagger UI to always be enabled, regardless of environment, to simplify API testing. Adjusted Dockerfile to only expose port 8080 in the final stage for better clarity and alignment with runtime requirements.
> refactor: always enable Swagger UI and adjust Docker ports

- helm-chart/.helmignore
- helm-chart/Chart.yaml
- helm-chart/templates/NOTES.txt
- helm-chart/templates/_helpers.tpl
- helm-chart/templates/deployment.yaml
- helm-chart/templates/hpa.yaml
- helm-chart/templates/ingress.yaml
- helm-chart/templates/service.yaml
- helm-chart/templates/serviceaccount.yaml
- helm-chart/templates/tests/test-connection.yaml
- helm-chart/values.yaml
Introduce Helm chart configurations for deploying the "evil-giraf" application on Kubernetes. Includes templates for service, deployment, ingress, service account, HPA, and testing, as well as customizable values and helper functions. This setup enables easier application management and deployment through Helm.
Closes #10
> feat: add Helm chart for evil-giraf application

- .github/workflows/build-latest.yml
Renamed the workflow and job from "Build" to "Build Latest" for clarity. This ensures better distinction when viewing workflows in the repository. No functional changes were introduced.
> chore(ci): update build latest workflow and job names to "Build Latest"

- EvilGiraf.IntegrationTests/ApplicationControllerTests.cs
- EvilGiraf.IntegrationTests/SubstituteWebApplicationFactory.cs
Replaced `WebApplicationFactory` with `SubstituteWebApplicationFactory` to enable service substitution using NSubstitute. Updated tests to use the substituted `IKubernetes` service, allowing better control and isolation of Kubernetes-related dependencies. Simplified client creation in tests by utilizing the new factory.
> refactor(test): introduce service substitution in tests

- EvilGiraf.Tests/DeploymentTests.cs
- EvilGiraf/Interface/IDeploymentService.cs
- EvilGiraf/Service/DeploymentService.cs
This pull request introduces new functionality for reading Kubernetes deployments in the `EvilGiraf` project. The changes include adding a new `ReadDeployment` method to the `IDeploymentService` interface and implementing it in the `DeploymentService` class. Additionally, several unit tests have been added to ensure the correct behavior of the new method.
* [`EvilGiraf/Interface/IDeploymentService.cs`](diffhunk://#diff-16c403f0982b692823f0f77afd54dccb3c34464ee35b4f254aba15a9ead5c757R9): Added the `ReadDeployment` method to the `IDeploymentService` interface.
* [`EvilGiraf/Service/DeploymentService.cs`](diffhunk://#diff-02cdc6594c3102ede9efc5a7d72c29034ae011c71b9c7e30330ee833c7e003c8R63-R79): Implemented the `ReadDeployment` method to fetch a deployment by name and namespace, handling …
> feat: deployment service read

- .github/workflows/build.yml
- .github/workflows/deploy.yaml
- .github/workflows/sonarqube.yaml
Introduce a GitHub Actions workflow to automate deployments to Kubernetes. It triggers on `main` branch pushes or upon completion of the "Build" workflow. The workflow uses Helm for deploying and supports dynamic image tags based on the latest commit SHA.
Closes #36
> feat(ci): add Kubernetes deployment workflow

- .github/workflows/build.yml
- .github/workflows/ci.yml
Updated GitHub workflows to trigger only on 'main' branch pushes and pull requests. This ensures CI processes run more efficiently and avoids unnecessary runs on other branches.
> fix: restrict CI workflows to 'main' branch and pull requests

- .github/workflows/build.yml
Add Git user email and name configuration to ensure proper tagging during the release process in the GitHub Actions workflow. This prevents potential issues with missing user identity in CI environments.
> fix: configure Git user for tagging in CI

- .github/workflows/build.yml
Added support for leveraging Docker build cache from the remote registry to speed up builds. Updated workflow to pull the latest image before building and include inline cache to improve efficiency.
> ci: optimize Docker image build with cache

- .github/workflows/sonarqube.yaml
The SonarQube key was changed to match the correct project identifier. Additionally, the `sonar.scanner.scanAll` parameter was added to ensure all files are included in the scan.
> fix: update SonarQube project key and add scanAll parameter

- EvilGiraf.Tests/ApplicationServiceTests.cs
- EvilGiraf.Tests/DeploymentTests.cs
- EvilGiraf/Interface/IApplicationService.cs
- EvilGiraf/Interface/IDeploymentService.cs
- EvilGiraf/Model/DeploymentModel.cs
- EvilGiraf/Service/ApplicationService.cs
- EvilGiraf/Service/DeploymentService.cs
Updated services and tests to return `null` instead of throwing exceptions when entities like applications or deployments are not found. This change ensures cleaner error handling and simplifies the codebase. Adjusted corresponding interfaces, methods, and unit tests to align with the new behavior.
> refactor: replace exceptions with null returns for not found cases

- .github/workflows/build.yml
Moved the Git tag creation step to occur after the Docker image push step. This ensures the tag is created only when the image has been successfully pushed to the registry. Improves workflow reliability and avoids incomplete releases.
> ci: reorder git tag creation step

- EvilGiraf/Controller/ApplicationController.cs
Introduce a new ApplicationController to handle application-level requests. This controller utilizes dependency injection for the IApplicationService interface, ensuring better modularity and testability.
Closes #66
> feat: add ApplicationController with dependency injection

- EvilGiraf.IntegrationTests/ApplicationControllerTests.cs
- EvilGiraf/Controller/ApplicationController.cs
This pull request adds new functionality to the `ApplicationController` and its corresponding integration tests in `ApplicationControllerTests`. The most important changes include the addition of a `Get` method to retrieve an application by its ID and the corresponding tests to ensure the new functionality works correctly.
* Added a `Get` method to retrieve an application by its ID. This method returns an `Ok` status with the application data if found, or a `NotFound` status with an error message if the application does not exist.
* Added a test `Get_ShouldReturnApplication` to verify that the `Get` method returns the correct application data and a status code of `Ok` when the application exists.
* Added a test `GetWithNonExistingId_ShouldReturnNotFound` to verify that the `Get` method …
> feat: Created route to get Application

- .github/workflows/deploy.yaml
- EvilGiraf.IntegrationTests/ApplicationControllerTests.cs
- EvilGiraf.IntegrationTests/AuthenticatedTestBase.cs
- EvilGiraf.IntegrationTests/AuthenticationTests.cs
- EvilGiraf.IntegrationTests/CustomWebApplicationFactory.cs
- EvilGiraf.IntegrationTests/DeploymentControllerTests.cs
- EvilGiraf/Authentication/ApiKeyAuthExtensions.cs
- EvilGiraf/Authentication/ApiKeyAuthHandler.cs
- EvilGiraf/Authentication/ApiKeyAuthOptions.cs
- EvilGiraf/Controller/ApplicationController.cs
- EvilGiraf/Controller/DeploymentController.cs
- EvilGiraf/Program.cs
- helm-chart/templates/deployment.yaml
- helm-chart/values.yaml
Introduced API Key-based authentication to enhance security across endpoints, with support for verification and Swagger integration. Updated integration tests and Helm charts to include key handling and validation. Controllers now enforce authorization through the new schema.
Closes #88
> feat: add API Key authentication for securing endpoints

- helm-chart/templates/deployment.yaml
The EF migrations command now uses the full path to the dotnet-ef tool, resolving potential issues with environment-dependent configurations. This ensures the migration command executes reliably and consistently.
> fix: update EF migrations command with correct dotnet-ef path

- helm-chart/templates/deployment.yaml
Adjusted the EF migrations command path from `~/.dotnet` to `/root/.dotnet` to ensure compatibility with the container's directory structure. This resolves potential issues during database migration execution.
> fix: correct EF migrations command path

- helm-chart/templates/rbac.yaml
Introduce ClusterRole and ClusterRoleBinding templates to the Helm chart. These define permissions for namespaces, pods, configmaps, secrets, services, ingresses, and deployments. Ensures proper access control and aligns with Kubernetes best practices.
> feat: add RBAC templates in helm chart for cluster roles

- EvilGiraf.IntegrationTests/DeploymentControllerTests.cs
- EvilGiraf.Tests/KubernetesTests.cs
- EvilGiraf/Controller/DeploymentController.cs
- EvilGiraf/Interface/IKubernetesService.cs
- EvilGiraf/Program.cs
- EvilGiraf/Service/KubernetesService.cs
Introduce `KubernetesService` to manage application deployments via `IDeploymentService`. Updated `DeploymentController` with a new endpoint to fetch deployment status and integrated `KubernetesService` into deployment tasks. Added unit and integration tests for deployment and status handling.
Closes #109
> feat: add deployment status route

- EvilGiraf.IntegrationTests/ApplicationControllerTests.cs
- EvilGiraf.Tests/ApplicationServiceTests.cs
- EvilGiraf/Controller/ApplicationController.cs
- EvilGiraf/Interface/IApplicationService.cs
- EvilGiraf/Service/ApplicationService.cs
This pull request introduces new functionality to list applications and includes several related changes across multiple files. The most important changes are the addition of new methods and tests for listing applications.
* [`EvilGiraf/Controller/ApplicationController.cs`](diffhunk://#diff-bc696ba179cc89bff2b9790a26d4e4f57733d34afb290ff377446fa4577f6b92R60-R68): Added a new `List` method to the `ApplicationController` to handle GET requests and return a list of applications.
* [`EvilGiraf/Interface/IApplicationService.cs`](diffhunk://#diff-9eb241e00a1d072ed8efebd7247803d15e31533d4629d21fa589522be74f4453R15-R16): Added a new `ListApplications` method to the `IApplicationService` interface.
* [`EvilGiraf/Service/ApplicationService.cs`](diffhunk://#diff-95eea49efe747bf2736104f00deb191b248bae …
> 108 application controller list

- EvilGiraf.IntegrationTests/DeploymentControllerTests.cs
- EvilGiraf/Controller/DeploymentController.cs
Updated deployment endpoints to use a more concise route format. Replaced `/application/{id}/deploy` with `/deploy/{id}` for both POST and GET methods, ensuring consistency across the API. Adjusted integration tests accordingly to align with the new routes.
> refactor: simplify deployment endpoint routes

- EvilGiraf.IntegrationTests/DeploymentControllerTests.cs
- EvilGiraf/Controller/DeploymentController.cs
Adjusted the status code to return 204 No Content instead of 404 Not Found when an application exists but is not deployed. This aligns the response with expected standards and avoids misleading error handling.
Closes #117
> refactor: update status code for non-deployed application check

- EvilGiraf.IntegrationTests/ApplicationControllerTests.cs
- EvilGiraf.IntegrationTests/DeploymentControllerTests.cs
- EvilGiraf.Tests/ApplicationServiceTests.cs
- EvilGiraf.Tests/KubernetesTests.cs
- EvilGiraf/Dto/ApplicationDto.cs
- EvilGiraf/Extensions/ApplicationExtensions.cs
- EvilGiraf/Migrations/20250206162202_InitialCreate.Designer.cs
- EvilGiraf/Migrations/20250206162202_InitialCreate.cs
- EvilGiraf/Migrations/DatabaseServiceModelSnapshot.cs
- EvilGiraf/Model/Application.cs
- EvilGiraf/Service/ApplicationService.cs
This pull request includes several changes to the integration and unit tests for the `ApplicationController` and `DeploymentController` classes. The main update is the addition of a new `Ports` property to the `ApplicationCreateDto` and `ApplicationUpdateDto` classes, which is now included in various test methods to ensure proper handling of this new property.
* Added `Ports` property to test cases in `EvilGiraf.IntegrationTests/ApplicationControllerTests.cs` to verify creation, retrieval, updating, and deletion of applications, ensuring the `Ports` property is correctly handled. [[1]](diffhunk://#diff-d41f11456c621976336f13cf3d5fd3b37b8b6fa73ae592bb6cb9e2c180b36a1bL24-R24) [[2]](diffhunk://#diff-d41f11456c621976336f13cf3d5fd3b37b8b6fa73ae592bb6cb9e2c180b36a1bR39) …
> 97 container port config

- EvilGiraf/Controller/DeploymentController.cs
Added a 204 response type to indicate no content when applicable for the Status endpoint in DeploymentController. This improves API response clarity and aligns with REST standards.
> chore: add 204 response type to Status endpoint

- .github/workflows/CI.yml
- EvilGiraf/Migrations/20250206162202_InitialCreate.Designer.cs
- EvilGiraf/Migrations/20250206162202_InitialCreate.cs
- EvilGiraf/Migrations/20250401064046_ApplicationPorts.Designer.cs
- EvilGiraf/Migrations/20250401064046_ApplicationPorts.cs
The Ports column was removed in an earlier migration and is now reintroduced with a default value of an empty array. This ensures consistent handling of application port data in the database schema.
> fix: add migration for Ports column in Applications

- EvilGiraf/Model/ApplicationType.cs
Added a JsonStringEnumConverter to the ApplicationType enum to enable JSON serialization and deserialization using string values instead of numerical indices. This improves clarity and interoperability when exchanging data in JSON format.
Closes #121
> feat: add JSON string enum converter to ApplicationType

- .github/workflows/CI.yml
Renamed existing jobs for clarity and introduced separate lint and build jobs for the frontend. Made tagging of Docker images resilient to errors by adding fallback with `|| true`. This ensures better modularity and reliability in CI execution.
> ci: restructure workflows and add frontend jobs

- helm-chart/templates/tests/test-connection.yaml
Updated the connection label to use "evil-giraf.api.labels" for consistency with the API structure. Adjusted the test command's connection URL to include the "-api" suffix, aligning it with the expected service name.
> fix: helm update test labels and connection URL for API

- .github/workflows/CI.yml
- EvilGiraf.Front/.env
- EvilGiraf.Front/src/lib/api.ts
- EvilGiraf.Front/vite.config.ts
- EvilGiraf.IntegrationTests/ApplicationControllerTests.cs
- EvilGiraf.IntegrationTests/AuthenticationTests.cs
- EvilGiraf.IntegrationTests/DeploymentControllerTests.cs
- EvilGiraf/Controller/ApplicationController.cs
- EvilGiraf/Controller/DeploymentController.cs
- helm-chart/templates/NOTES.txt
Standardizes all API routes under an '/api' prefix for consistency and clarity. Adjusted tests, environment variables, and proxy configurations to accommodate the new route structure. Also removed redundant SonarQube caching steps in CI workflow.
> refactor: update API routes to include '/api' prefix

- helm-chart/templates/_helpers.tpl
Updated the serviceAccountName logic to use `.Values.front` instead of `.Values.api` for consistency with the front-end configuration. This resolves potential misconfigurations when managing service accounts in the Helm chart.
> fix: helm correct front serviceAccountName value reference

- .github/workflows/CD.yaml
Repositioned the Git tag creation step for better sequencing in the CD pipeline. This ensures tagging occurs after all deployment steps, aligning with expected release flow.
> refactor: CD move Git tag creation to the end of the workflow

- EvilGiraf.IntegrationTests/DeploymentControllerTests.cs
Modified deployment response assertions to allow greater flexibility in test validation. Ensured the test verifies a minimum response count and checks for matching deployment status equivalence. This improves test robustness and accommodates potential future changes.
> refactor: update deployment tests for flexible assertions

- EvilGiraf.IntegrationTests/DeploymentControllerTests.cs
- EvilGiraf.Tests/DeploymentTests.cs
- EvilGiraf.Tests/KubernetesTests.cs
- EvilGiraf/Controller/DeploymentController.cs
- EvilGiraf/Interface/Kubernetes/IDeploymentService.cs
- EvilGiraf/Interface/Kubernetes/INamespaceService.cs
- EvilGiraf/Program.cs
- EvilGiraf/Service/Kubernetes/DeploymentService.cs
- EvilGiraf/Service/Kubernetes/NamespaceService.cs
- EvilGiraf/Service/KubernetesService.cs
Added `NamespaceService` to handle Kubernetes namespace operations, including creation and retrieval. Updated `KubernetesService` to leverage `NamespaceService` for namespace management to improve modularity and code clarity. Refactored interfaces and services to align with the new namespace handling logic.
> feat: introduce namespace management service

- EvilGiraf.IntegrationTests/DeploymentControllerTests.cs
- EvilGiraf.Tests/KubernetesTests.cs
- EvilGiraf.Tests/ServiceTests.cs
- EvilGiraf/Interface/Kubernetes/IServiceService.cs
- EvilGiraf/Model/ServiceModel.cs
- EvilGiraf/Program.cs
- EvilGiraf/Service/Kubernetes/ServiceService.cs
- EvilGiraf/Service/KubernetesService.cs
This pull request introduces a new `IServiceService` interface and its implementation to manage Kubernetes services, along with corresponding unit tests. The changes also include updates to the `KubernetesService` to utilize the new `IServiceService` for creating and updating services.
* [`EvilGiraf/Interface/Kubernetes/IServiceService.cs`](diffhunk://#diff-154a1fe011319bca058fd1a594a36bc984957706085010305a2df267c353256dR1-R17): Added a new interface `IServiceService` for managing Kubernetes services, including methods for creating, reading, updating, deleting, and conditionally creating services.
* [`EvilGiraf/Service/Kubernetes/ServiceService.cs`](diffhunk://#diff-e9d17025f01909ae17699bde88d1c4a52d9172149cec375009b361089458a998R1-R68): Implemented the `IServiceService` interface with …
> 98 service creation

- EvilGiraf.IntegrationTests/DeploymentControllerTests.cs
- EvilGiraf.Tests/NamespaceServiceTests.cs
- EvilGiraf/Controller/DeploymentController.cs
- EvilGiraf/Interface/IKubernetesService.cs
- EvilGiraf/Interface/Kubernetes/INamespaceService.cs
- EvilGiraf/Service/Kubernetes/NamespaceService.cs
- EvilGiraf/Service/KubernetesService.cs
Introduce `DeleteNamespace` in `NamespaceService` for namespace removal. Update `DeploymentController` and `KubernetesService` to include undeploy logic. Adjust deployment endpoint to return `202 Accepted` for async operations.
Closes #143 
Closes #141
> feat: add namespace deletion and adjust deployment logic

- EvilGiraf.Front/Dockerfile
- EvilGiraf.Front/src/lib/api.ts
- EvilGiraf.Front/src/pages/ApplicationDetails.tsx
Enhanced deployment and undeployment mutations to poll for status updates until success or a defined timeout. This ensures the frontend accurately reflects the deployment state by repeatedly querying the API. Added handling for empty deployment status responses to improve resilience.
> chore: add polling mechanism for deployment status updates

- EvilGiraf.IntegrationTests/ApplicationControllerTests.cs
- EvilGiraf.IntegrationTests/DeploymentControllerTests.cs
- EvilGiraf.Tests/ApplicationTests.cs
- EvilGiraf.Tests/DeploymentTests.cs
- EvilGiraf.Tests/GitBuildTests.cs
- EvilGiraf.Tests/KubernetesTests.cs
- EvilGiraf.Tests/ServiceTests.cs
- EvilGiraf/Dto/ApplicationDto.cs
- EvilGiraf/Extensions/ApplicationExtensions.cs
- EvilGiraf/Migrations/20250413135706_ApplicationSinglePort.Designer.cs
- EvilGiraf/Migrations/20250413135706_ApplicationSinglePort.cs
- EvilGiraf/Model/Application.cs
- EvilGiraf/Model/DeploymentModel.cs
- EvilGiraf/Model/ServiceModel.cs
- EvilGiraf/Service/ApplicationService.cs
- EvilGiraf/Service/KubernetesService.cs
This update modifies the `Application` model to use a single nullable `Port` instead of a collection of `Ports`. Related services, DTOs, and tests have been updated accordingly. Migration added to reflect this schema change.
> refactor: replace multiple ports with single port in Application

- EvilGiraf.Front/src/pages/ApplicationDetails.tsx
- EvilGiraf.Front/src/pages/Applications.tsx
- EvilGiraf.Front/src/types/api.ts
- EvilGiraf.Tests/ApplicationTests.cs
- EvilGiraf/Service/ApplicationService.cs
Replaced multi-port support with a single nullable port across the application. Updated backend validation to set port to null if a negative value is provided and adjusted frontend to handle the change in port data structure. Updated tests to reflect the new behavior.
> feat: front update application port logic to support single nullable port

- .github/workflows/CD.yaml
- helm-chart/templates/deployment-api.yaml
- helm-chart/values.yaml
Introduce configuration options for Docker registry URL, username, and password in Helm values and GitHub Actions workflow. These values are also set as environment variables in the API deployment template to support authenticated Docker registry access.
> fix: add Docker registry configuration to API deployment

- EvilGiraf.IntegrationTests/DeploymentControllerTests.cs
- EvilGiraf.Tests/IngressTests.cs
- EvilGiraf.Tests/KubernetesTests.cs
- EvilGiraf.Tests/ServiceTests.cs
- EvilGiraf/Interface/Kubernetes/IDeploymentService.cs
- EvilGiraf/Interface/Kubernetes/IIngressService.cs
- EvilGiraf/Interface/Kubernetes/IServiceService.cs
- EvilGiraf/Service/Kubernetes/ConfigMapService.cs
- EvilGiraf/Service/Kubernetes/DeploymentService.cs
- EvilGiraf/Service/Kubernetes/IngressService.cs
- EvilGiraf/Service/Kubernetes/ServiceService.cs
- EvilGiraf/Service/KubernetesService.cs
Refactored `CreateIfNotExists` methods to `CreateOrReplace` for deployments, services, ingress, and config maps to streamline resource management. Updated tests accordingly to reflect the new behavior and ensure proper replacements or creations are handled consistently across resources.
Closes #157 
Closes #158
> feat: implement createOrReplace functionality for resources

- EvilGiraf.Tests/IngressTests.cs
- EvilGiraf/Model/Kubernetes/IngressModel.cs
- EvilGiraf/Service/Kubernetes/IngressService.cs
- EvilGiraf/appsettings.json
- helm-chart/templates/deployment-api.yaml
- helm-chart/values.yaml
Introduced the ability to define custom annotations for Kubernetes ingress objects by integrating configuration support. Updated `IngressService`, model, templates, and tests to handle annotations and TLS configurations dynamically. This enhancement improves flexibility and ease of management for ingress resources.
Closes #153
> feat: add support for custom ingress annotations

- EvilGiraf/appsettings.json
- helm-chart/templates/deployment-api.yaml
- helm-chart/values.yaml
Ingress annotations logic was removed from Helm chart values and templates, streamlining configuration. These annotations are now directly defined in `appsettings.json`, centralizing their management. This simplifies the deployment process and avoids redundant configuration.
> refactor: remove Helm chart ingress annotations configuration

- helm-chart/templates/rbac-front.yaml
Expanded RBAC rules to include permissions for managing batch jobs. This allows the service to get, list, watch, create, update, patch, and delete job resources.
> feat: add permissions for batch jobs

- EvilGiraf.Front/src/lib/api.ts
Added `isAsync=false` query parameter to deployment API calls to ensure deployments are handled synchronously. This avoids potential issues caused by asynchronous processing in certain workflows.
> fix: front ensure synchronous deployment by default

- helm-chart/templates/rbac-api.yaml
- helm-chart/templates/rbac-front.yaml
Removed job-related permissions from the front role and added them to the api role. This ensures proper alignment of RBAC configurations with their respective responsibilities. No functional changes expected outside of corrected scoping.
> fix: adjust job permissions between front and api roles

- .github/workflows/CD.yaml
Updated the CD pipeline to wrap Helm's `--set` values in single quotes. This ensures proper parsing of variables and prevents potential deployment issues caused by unquoted values.
> fix: wrap helm set values in quotes to handle parsing issues

- .github/workflows/CD.yaml
The Helm `--set` parameters were updated to include single quotes around values. This ensures proper handling of special characters and prevents potential parsing issues during deployment.
> fix: add quotes to Helm set parameters in workflow
